-- AlterTable
ALTER TABLE "Cohort" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updatedAt" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "DeliveryLog" ALTER COLUMN "date" SET DEFAULT CURRENT_TIMESTAMP;
