export default {
  EMAIL_REQUIRED: 'Email is required',
  PASSWORD_REQUIRED: 'Password is required',
  EMAIL_FORMATING: 'Email format invalid',
  PASSWORD_REQUIREMENTS:
    'Password must contain at least one upper case character, at least one number, at least one special character and not be less than 8 characters in length.',
  POST_NOT_FOUND: 'Post not found by that Id ',
  USER_NOT_FOUND: 'User not found by that Id',
  REQUEST_FORBIDDEN: 'User does not have access for request',
  EMAIL_PASS_INVALID: 'The email or password is incorrect',
  NOT_AUTHORISED: 'You are unauthorised to make that change',
  INCOMPLETE_REQUEST: 'Missing fields, required to perform this action',
  BAD_REQUEST: 'Wrong argument provided in the request',
  COHORT_NOT_FOUND: 'No cohort with the provided ID exists',
  INCOMPLETE_DELIVERY_LOG_REQUEST:
    'Cohort ID AND log-lines must be provided in order to create a delivery log',
  DELIVERY_LOG_GENERIC_ERROR:
    'An error occurred while creating the delivery log.',
  DATE_FORMATTING: 'Invalid date format. Please use yyyy/mm/dd.',
  DATE_REQUIRED: 'Date is required',
  EMAIL_IN_USE: 'This email address is already in use',
  UNABLE_TO_CREATE_USER: 'Unable to create new user',
  MISSING_AUTH_HEADER: 'No authorisation header',
  TOKEN_FAILED: 'Missing or invalid token',
  INTERNAL_ERROR: 'The server was unable to complete this request',
  MISSING_CONTENT: 'The content is missing from the request body',
  INVALID_NOTE_CONTENT: 'Some text must be provided in order to create a note',
  UNABLE_TO_CREATE_COHORT: 'Unable to create a new cohort.',
  NAME_REQUIRED: 'A name must be provided.',
  NAME_FORMATTING: 'Names can only contain letters',
  UNABLE_TO_SEARCH_USER: 'Unable to search for users',
  NAME_USER_NOT_FOUND: 'user not found by that name',
  UNABLE_TO_GET_USER: 'Unable to get the user',
  UNABLE_TO_UPDATE_POST: 'Unable to update post'
}
